language: node_js
node_js:
  - 14
os: linux
arch: amd64
branches:
  only:
    - master
cache:
  directories:
    - node_modules
script:
  - npm run test
  - npm run build
deploy:
  provider: pages:git
  edge: true
  token: $GH_TOKEN
  verbose: true